export const projects = [
  { title: "По проекту", link: "/on-project", id: 1 },
  { title: "Объекты", link: "/objects", id: 2 },
  { title: "РД", link: "/rd", id: 3 },
  { title: "МТО", link: "/mto", id: 4 },
  { title: "СМР", link: "/view", id: 5 },
  { title: "График", link: "/chart", id: 6 },
  { title: "МиМ", link: "/mim", id: 7 },
  { title: "Рабочие", link: "/workers", id: 8 },
  { title: "Капвложения", link: "/cap-investments", id: 9 },
  { title: "Бюджет", link: "/budget", id: 10 },
  { title: "Финансирование", link: "/financing", id: 11 },
  { title: "Панорамы", link: "/panoramas", id: 12 },
  { title: "Камеры", link: "/cameras", id: 13 },
  { title: "Поручения", link: "/assignments", id: 14 },
  { title: "Контрагенты", link: "/contractors", id: 15 },
];
