export const projects = [
  { title: "По проекту", link: "/test", id: 1 },
  { title: "Объекты", link: "/test", id: 2 },
  { title: "РД", link: "/test", id: 3 },
  { title: "МТО", link: "/test", id: 4 },
  { title: "СМР", link: "/", id: 5 },
  { title: "График", link: "/test", id: 6 },
  { title: "МиМ", link: "/test", id: 7 },
  { title: "Рабочие", link: "/test", id: 8 },
  { title: "Капвложения", link: "/test", id: 9 },
  { title: "Бюджет", link: "/test", id: 10 },
  { title: "Финансирование", link: "/test", id: 11 },
  { title: "Панорамы", link: "/test", id: 12 },
  { title: "Камеры", link: "/test", id: 13 },
  { title: "Поручения", link: "/test", id: 14 },
  { title: "Контрагенты", link: "/test", id: 15 },
];
